print("Hello.I am JARVIS. I am a chatbot")
print("I like animal and I love to talk about movie")
name=input("What is your name?")
print("Hello",name,",nice to meet you")
print("I love Robert Downey Jr. and I also like MARVEL series movie")
movie=input("How about you? What is your favorite MARVEL's movie? ")
print("I like", movie, "too.")
question="Have you ever seen The Judge?"
everseen=input(question)
print("Interesting. Robert Downey Jr. has perfect act in that movie. Maybe we should go to the movies tomorrow as well!")